### ISSUE TITLE
Invalid cursor position

### ISSUE THREAD

**Issue by tdurieux** [phoboslab/jsmpeg-vnc#10]
Hi,

First, thanks for this awesome tools!

The position of the cursor is not correct when the output size (option -s) ratio (width/height) is not the same as the screen ratio.

Thanks

**Comment by phoboslab** [comment]
Thanks! The mouse position was actually wrong for any scaling that was not whole number (i.e. 2x, or 3x), due to an integer division truncating it.

**Comment by UltimaterBR** [comment]
Não estou entendendo pq vocês estão mandando emails para mim
Em 02/08/2015 15:45, "Dominic Szablewski" <notifications@github.com>
escreveu:
