### ISSUE TITLE
No menus displayed

### ISSUE THREAD

**Issue by techninja** [phoboslab/jsmpeg-vnc#16]
Testing application: Photoshop CC 2015, Windows 7 x64

It seems the screen capture is not getting any "native" menus, also seems to be missing a number of other "sub-window" type things in the app like property drawers, brush alternates, or even the open image itself. Hrmmm.

**Comment by phoboslab** [comment]
Again, disable Aero. The Aero compositer let's us only grab the window context, not what's overlayed on top (like separate file open menus). Or just grab the whole desktop and you should get everything (which, again, is slow with Aero).

**Comment by techninja** [comment]
My desktop is a full 4k, so.. I might skip that if I'm looking for performance. Though I do have another machine to test with. I wonder how well this will work on a non-virtual machine running headless through RDP....

**Comment by techninja** [comment]
The RDP session sucks and does not allow for standard operating. I'm starting to suspect that without a real monitor attached, there's no hope of using it as like this... of course you setup the virtual cloud machines for this.... HRMM...

**Comment by Moter8** [comment]
@techninja Tried disabling Aero? Shouldn't be thaat much of a change.

**Comment by techninja** [comment]
No Aero on the remote desktop session. I believe I'm likely going about it all wrong, will try again next week :)

**Comment by techninja** [comment]
I've gotten this to finally work after plugging in a monitor & disabling Aero. Now of course for some applications the menu bar is invisible, and child windows aren't visible. Perhaps what we need is a fullscreen capture mode than crops to a windows full bounds?

Also: Native cursors! Non existent for some/most games, but very important for most desktop apps.
