### ISSUE TITLE
invalid request 

### ISSUE THREAD

**Issue by michelthomas** [phoboslab/jsmpeg-vnc#17]
![default](https://cloud.githubusercontent.com/assets/13606025/9024291/f7e8c948-389d-11e5-879b-8eb7898c7848.PNG)
how to proceed? ... I did everything right

**Comment by UltimaterBR** [comment]
Your program is correct, but I did incorrect, but now I made sure.
 I just want to ask a deal the host has to have a computer that can
withstand the game he is hosteando right? And can you host for me?

2015-08-01 22:46 GMT-03:00 michelthomas <notifications@github.com>:

**Comment by UltimaterBR** [comment]
Hosting*


2015-08-01 23:48 GMT-03:00 Leonardo Silva de Jesus <boltleonardo@gmail.com>:

**Comment by michelthomas** [comment]
sim br está tudo correto,e o pc suporta o jogo/janela...só q não está conectando com o servidor

**Comment by UltimaterBR** [comment]
Você que fez esse programa?


2015-08-02 14:06 GMT-03:00 michelthomas <notifications@github.com>:

**Comment by michelthomas** [comment]
claro que não

**Comment by UltimaterBR** [comment]
Então porque está mandando emails para mim? Não estou entendendo oque está
acontecendo
Em 02/08/2015 15:47, "michelthomas" <notifications@github.com> escreveu:

**Comment by phoboslab** [comment]
@UltimaterBR unwatch this repository or change your [email settings](https://github.com/settings/notifications). And PLEASE write english in future.

Closing: derailed thread with no usable problem description or info.
