### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by dkrikun** [phoboslab/jsmpeg-vnc#19]
I'm trying to build this on Windows 7, fails to run due to missing `avcodec-57.dll` etc. I see there is `libavcodec.dll.a`, but I'm not sure how to use it.

**Comment by phoboslab** [comment]
The DLLs are included in the release: https://github.com/phoboslab/jsmpeg-vnc/releases

You can also get the latest versions from http://ffmpeg.zeranoe.com/builds/ - but you'd also have to link against these then.
