### ISSUE TITLE
stream over the internet?

### ISSUE THREAD

**Issue by azerty55** [phoboslab/jsmpeg-vnc#21]
ok, i know how vnc it work and i want to know if its possible to stream the signal over the internet, there is a command for ports but any port i have open give that possibiliy. Wich port must be forwarded to work over the internet? 
Thanks

**Comment by phoboslab** [comment]
You have to forward the port on your router that you specified when starting the app. I.e. in this example:

`jsmpeg-vnc.exe -b 2000 -s 640x480 -f 30 -p 9006 "Quake 3: Arena"`

you  have to forward port 9006. If you don't explicitly specify a port, jsmpeg-vnc uses port `8080`.
See the readme: https://github.com/phoboslab/jsmpeg-vnc/blob/master/README.md

**Comment by azerty55** [comment]
I already forward à specific port but its not working
Le 15 oct. 2015 11:19 PM, "Dominic Szablewski" <notifications@github.com> a
écrit :

**Comment by TheAngryAvocado** [comment]
@azerty55 Maybe you haven't opened that port from your router's settings. Google "your-router-model-here port forwarding"

**Comment by azerty55** [comment]
my port is forwarded, your system does not made to work over the internet

**Comment by azerty55** [comment]
ok i find the solution : forward a port and type ip address of router, not pc and it works, but its badly explained i find

**Comment by phoboslab** [comment]
Well, yeah, of course your local IP is not reachable from the public internet. You have to point your browser to the public IP of your network. Nice to know that it works, though!

**Comment by Mage-Enderman** [comment]
But TCP UDP Other or Both?

**Comment by azerty55** [comment]
For secure i forward both

**Comment by Mage-Enderman** [comment]
also, I've tried using the IP of the router for port forwarding but that doesn't work and the IP of my computer and the IP portchecktool.com and the IP that jsmpeg give me don't match up so which one should I port forward
