### ISSUE TITLE
Just screen share, do not allow control input?

### ISSUE THREAD

**Issue by MagnumDopus** [phoboslab/jsmpeg-vnc#31]
I would like to use this program only to share my screen with someone else but I do not want them to be able to control anything, nor do I want it to take over their control in anyway.  Is there any easy way to do this?

**Comment by rogerdg** [comment]
This would be useful.  If the PC doing the casting was not looking for input from the connected browser(s) it might speed up the connections when more than one browser is connected at a time.  Perhaps add a switch like -i  to turn off input, or leave input off by default and add -i to enable input if needed.

**Comment by phoboslab** [comment]
Added the `-i 0` option in the latest release. Thanks!

**Comment by MagnumDopus** [comment]
Dude you rule!  We use your software for our website to record game videos and other things, nothing beats it in terms of latency!
