### ISSUE TITLE
Has stopped working all together

### ISSUE THREAD

**Issue by MagnumDopus** [phoboslab/jsmpeg-vnc#33]
I recently grabbed the new version and backed up my old version.  However for whatever reason now nothing is transmitted.  I am not sure if this relies on depencies within windows which have changed but something is different and I have not altered any files.  My friend is having the same issue, when trying to share the screen now we only get either some iframe (I am assuming, its a static greenscreen with a few pixels showing) or a single still shot of the source we are trying to capture.  Using "cursor" and "desktop" have the same exact effect.  I wish I could provide some kind of bug report but there is nothing being reported as gone wrong.

**Comment by MagnumDopus** [comment]
My mistake, it seems to be an issue with chrome, it works with firefox.  My friend reported the same fix, so it seems chrome is not liking this anymore for whatever reason.

**Comment by BenNottelling** [comment]
Close this as it's not an issue with jsmpeg-vnc?
