### ISSUE TITLE
Msvcr100.dll is missing on windows server 2008 R2 a a

### ISSUE THREAD

**Issue by handsetvn** [phoboslab/jsmpeg-vnc#34]
![error](https://cloud.githubusercontent.com/assets/2859031/21714198/53b8ff70-d430-11e6-91f7-be7b676df59b.jpg)
can anyone help me with this issue? Thanks in advance

**Comment by phoboslab** [comment]
You need the [Microsoft Visual C++ 2010 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=5555).

**Comment by handsetvn** [comment]
@phoboslab  After Install Microsoft Visual C++ 2010 Redistributable Package.i have got an error as attachment file below.
![error2jpg](https://cloud.githubusercontent.com/assets/2859031/21758629/319e4fca-d670-11e6-90c5-3f94e3a5e551.png)

**Comment by phoboslab** [comment]
`"desktop"`. Lowercase.

**Comment by phoboslab** [comment]
Added info about the missing DLL to the readme.
