### ISSUE TITLE
How to run jsmpeg-vnc on windows 10

### ISSUE THREAD

**Issue by handsetvn** [phoboslab/jsmpeg-vnc#35]

**Comment by handsetvn** [comment]
@phoboslab  can you help me with this issue? Thanks in advance

**Comment by phoboslab** [comment]
What's the issue? It runs just fine on my Windows 10 installation.

**Comment by handsetvn** [comment]
@phoboslab  can you send to me the file build on Windows 10 ?

**Comment by phoboslab** [comment]
The latest build works on Windows 10: https://github.com/phoboslab/jsmpeg-vnc/releases/tag/v0.2

**Comment by phoboslab** [comment]
Closing for lack of info.
