### ISSUE TITLE
.h264 to mpeg1 format

### ISSUE THREAD

**Issue by PorkPiePie** [phoboslab/jsmpeg-vnc#50]
Hi,

I captured a render buffer target from my GPU and encoded it to a .h264 file. 
So, I'd like to know how can I transode my .h264 to mpeg1 video format so that I send it over websocket, decode and render?

**Comment by BenNottelling** [comment]
I guess I don't understand.. are you trying to send a video you've already recorded? This really isn't the project for that lol
