### ISSUE TITLE
unable to open index.html

### ISSUE THREAD

**Issue by luisaosan** [phoboslab/jsmpeg-vnc#6]
Happens to any device and or program i try to "attach"
also the warning of "data not aligned"
![captura de tela 2015-07-29 20 31 30](https://cloud.githubusercontent.com/assets/13561630/8972484/05ef7718-3631-11e5-9370-f78fdb90199e.png)

**Comment by phoboslab** [comment]
The `client` directory needs to be a subdirectory of the one where the `jsmpeg-vnc.exe` is in. I.e.:
```
jsmpeg-vnc/
	jmspeg-vnc.exe
	client/
		index.html
		jmspg.js
		jsmpg-vnc.js
```

The warning about unaligned data can be safely ignored.

**Comment by luisaosan** [comment]
everything was as it should be but for some reason i need to "cd" to the location to detect the client/index.html. Anyway, thanks :)
