### ISSUE TITLE
templates cannot be declared to have 'C' linkage when compiled in vs2017

### ISSUE THREAD

**Issue by FEYeh** [phoboslab/jsmpeg-vnc#60]
Error | C2894 | templates cannot be declared to have 'C' linkage | jsmpeg-vnc | c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\xtr1common | 334 |  
https://msdn.microsoft.com/library/95bhc9c2.aspx

**Comment by BenNottelling** [comment]
Project was made for vs2010 and compiles perfectly in it

**Comment by FEYeh** [comment]
Thanks a lot~!
:-)

**Comment by BenNottelling** [comment]
No problem! 😁
