### ISSUE TITLE
Uncaught DOMException: The operation is insecure.

### ISSUE THREAD

**Issue by graysuit** [phoboslab/jsmpeg-vnc#79]
In localhost (http), it shows fine.
But when port forward using ngrok (https), i see no video.

When I check console tab, it says `Uncaught DOMException: The operation is insecure.` at [jsmpg-vnc.js#L6](https://github.com/phoboslab/jsmpeg-vnc/blob/master/client/jsmpg-vnc.js#L6)

I check this open pull request, it solves my issue. 
Fix: [PR](https://github.com/phoboslab/jsmpeg-vnc/pull/58)

It simply replaces:
```js
var client = new WebSocket( 'ws://' + window.location.host + '/ws' );
```
with
```js
var client = new WebSocket(((window.location.protocol === 'https:') ? 'wss://' : 'ws://') + window.location.host + '/ws' );
```

**Comment by phoboslab** [comment]
This whole thing needs a big overhaul and I'm currently not very interested in doing that. I merged the PR, though :)
