### ISSUE TITLE
Jsmpeg-vnc does not launch

### ISSUE THREAD

**Issue by rikrik97** [phoboslab/jsmpeg-vnc#8]
I downloed the version 0.1 and i click on the exe jsmpeg-vnc, a window of cmd apens for a second and then closes with no message problem, nothing, help me, i really want to try this

**Comment by krist666** [comment]
Open cmd.exe, then type for example: C:\Users\User\Downloads\jsmpeg-vnc-v0.1\jsmpeg-vnc.exe -s 1280x720 desktop
