### ISSUE TITLE
VNC is not VNC

### ISSUE THREAD

**Issue by goshante** [phoboslab/jsmpeg-vnc#86]
You have a "VNC" in your project's name, but what about actual VNC? Why I cannot connect to my server via VNC client? Only browser HTTP works

**Comment by phoboslab** [comment]
I foolishly chose that name to convey that this project provides similar functionality to VNC. It does not support the VNC protocol. Sorry for the confusion.

I have no plans to work on this particular project again, as I have long abandoned Windows.
