### ISSUE TITLE
Can't connect to my ip, tried from phone and pc.

### ISSUE THREAD

**Issue by krist666** [phoboslab/jsmpeg-vnc#9]
![halp](https://cloud.githubusercontent.com/assets/13568654/8979309/dbe70006-36b9-11e5-939c-999e307404d9.jpg)

**Comment by phoboslab** [comment]
`cd` into the directory containing the `jsmpeg-vnc.exe` before executing it, otherwise it can't find the `client/` data.

**Comment by krist666** [comment]
I dont know how to cd, or what ever is that, can you explain how to do it please?(Sorry for taking your time, eng as second lang)

**Comment by macsj200** [comment]
It's a terminal command, it means [change directory](https://en.wikipedia.org/wiki/Cd_(command)).  On windows, search for cmd and open it, then type `chdir C:\path\to\folder`

**Comment by krist666** [comment]
It worked, thanks!
